import React from 'react'

export default function TermsOfSale() {
    return (
        <section className="banner-section" style={{ "backgroundImage": "url(assets/images/metaspace/31_Rotation_star_small_mp4.mp4)" }}>
            <div className="container">
                <div className="pt-5">
                    <div className="banner-content text-center top-section w-100" style={{ marginLeft: "0px" }}>
                        <div className="topSection m-3" style={{ background: "rgba(0,0,0,0.9)" }}>
                        <img className="w-50 meta m-4" src="assets/images/logo/logo-white.svg"></img>
                            
                            <div className="row">
                                <div className="col-12">
                                    <p className="fs-1">Terms of Sale</p>
                                    <p className="fs-6">(“Randomizer Network,” “we,” “us,” or “our”) provides its services (described below) and related content to you (“you” or “User”) through its website and platform for Meta Pass located at randomizer.network (the “Site”), subject to these Terms of Use (as amended from time to time, the “Terms”). The Privacy Policy and all such additional terms, guidelines, and rules as set forth on the Site are hereby incorporated by reference into these Terms and expressly agreed to and acknowledged by you. These terms govern your access to and use of this Site, as well as all content, functionality, and services offered on or through the Site, including Perks (as defined below) (collectively, the “Services”), and Randomizer Network Collective NFTs. By signing up for an account on the Site, connecting your cryptocurrency wallet (e.g., MetaMask or WalletConnect) to the Services, or otherwise using or accessing the Services, Perks or any Meta Pass NFTs, you acknowledge that you have read and agree to these Terms.</p>

                                    <p className="fs-6">By agreeing to these Terms, you hereby certify that you are at least 18 years of age. If you do not agree to these Terms, you must not access or use the Site.</p>

                                    <p className="fs-6">PLEASE READ THESE TERMS CAREFULLY, AS THEY CONTAIN AN AGREEMENT TO ARBITRATE AND OTHER IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES, AND OBLIGATIONS. THE AGREEMENT TO ARBITRATE REQUIRES (WITH LIMITED EXCEPTION) THAT YOU SUBMIT CLAIMS YOU HAVE AGAINST US TO BINDING AND FINAL ARBITRATION, AND FURTHER (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AGAINST Randomizer Network ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING, (2) YOU WILL ONLY BE PERMITTED TO SEEK RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ON AN INDIVIDUAL BASIS, AND (3) YOU MAY NOT BE ABLE TO HAVE ANY CLAIMS YOU HAVE AGAINST US RESOLVED BY A JURY OR IN A COURT OF LAW.</p>

                                    <p className="fs-6">We reserve the right, at our sole discretion, to change or modify portions of these Terms at any time. If we do this, we will post the changes on this page and will indicate at the top of this page the date these Terms were last revised. We will also notify you, either through the Site user interface, in an email notification or through other reasonable means. Any such changes will become effective no earlier than fourteen (14) days after they are posted, except that changes addressing new functions of the Site will be effective immediately. Your continued use of the Site after the date any such changes become effective constitutes your acceptance of the new Terms of Use.</p>

                                    <p className="fs-6">SMART CONTRACT ENABLED</p>
                                    <p className="fs-6">A Meta Pass NFT is a non-fungible Ethereum-based token that uses smart contracts on the Ethereum blockchain (“Smart Contracts”). The Ethereum blockchain provides an immutable ledger of all transactions that occur on the blockchain. This means that all Meta Pass NFTs are outside of the control of any one party, including Randomizer Network, and are subject to many risks and uncertainties. Randomizer Network neither owns nor controls MetaMask, WalletConnect, the Ethereum network, your browser, or any other third party site, product, or service (including third party wallets or marketplaces) that you might access, visit, or use for the purpose of enabling you to use the Services or to purchase, list, auction, or sell Meta Pass NFTs (“Transaction”), and that, except with respect to transferring control of a Meta Pass NFT to the initial purchaser through the Services (“Initial Purchaser”), Randomizer Network has no responsibility with respect to any Transaction. Randomizer Network will not be liable for the acts or omissions of any third parties, nor will Randomizer Network be liable for any damage that you may suffer as a result of your transactions or any other interaction with any third parties. You understand that your Ethereum public address will be made publicly visible whenever you engage in a Transaction. Aside from transferring control of the Meta Pass NFT to the Initial Purchaser, Randomizer Network has no control over the transfer, storage, ownership or maintenance of the Meta Pass NFT.</p>

                                    <p className="fs-6">Changes to services</p>
                                    <p className="fs-6">Randomizer Network reserves the right to modify or discontinue, temporarily or permanently, the Services (or any part thereof) with or without notice. You agree that Randomizer Network will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Services, including in relation to any Meta Pass NFT.</p>

                                    <p className="fs-6">Randomizer Network Perks</p>
                                    <p className="fs-6">A Collector (as defined below) of a Meta Pass NFT may receive special perks, experience, or opportunities as determined by Randomizer Network in its sole discretion (“Perks”) after the Meta Pass NFTs are first made available for sale (i.e., dropped) by Randomizer Network. Randomizer Network does not make any representation or guarantee that any Collector will receive any Perks or achieve any particular outcome as a result of owning any Meta Pass NFT. Randomizer Network reserves the right, at its sole discretion, to restrict, limit, or deny any Perks to any Collector, including to limit the period of time when a Perk is available, for any reason, at any time. Perks are not intended to be an endorsement of any project, creator, NFT, individual or any other thing, and Randomizer Network makes no recommendation and provides no investment advice in connection with any Perks or otherwise as a result of holding or owning the Meta Pass NFT.</p>

                                    <p className="fs-6">Connecting your wallet</p>
                                    <p className="fs-6">In order to access and use the Services, including engaging in a Transaction on the Services, you must connect your account to your digital wallet supported on MetaMask, WalletConnect or other wallet extensions or gateways as allowed on the Services. Such digital wallets allow you to purchase, store, and engage in transactions using the native Ethereum cryptocurrency, ETH. When you link your cryptocurrency wallet, you understand and agree that you are solely responsible for maintaining the security of your wallet and your control over any wallet-related authentication credentials, private or public cryptocurrency keys, non-fungible tokens or cryptocurrencies that are stored in or are accessible through your wallet. Any unauthorized access to your cryptocurrency wallet by third parties could result in the loss or theft of Meta Pass NFTs and/or funds held in your wallet and any associated wallets, including any linked financial information such as bank account(s) or credit card(s). Randomizer Network is not responsible for managing and maintaining the security of your cryptocurrency wallet. Randomizer Network has no responsibility or liability to you for any unauthorized access to or use of your cryptocurrency wallet or if you are unable to locate your credentials. If you notice any unauthorized or suspicious activity in your cryptocurrency wallet that seems to be related to the Services, please notify us immediately.</p>

                                    <p className="fs-6">Sale of Meta Pass NFT</p>
                                    <p className="fs-6">When each Meta Pass NFT is sold for the first time, the agreement for sale is between Randomizer Network and the Initial Purchaser. If the Initial Purchaser decides to sell a Meta Pass NFT (“Secondary Sale”), then Randomizer Network is not a party to any agreement between the applicable buyer, seller, or facilitator of the Secondary Sale.</p>

                                    <p className="fs-6">If you or any owner of a Meta Pass NFT (“Collector”) sells or transfers a Meta Pass NFT to another collector, (a) then you, as Collector, represent and warrant that you will notify the subsequent collector of these Terms and require the subsequent collector to comply with these Terms, (b) the Collector License (as defined below) as set forth herein will automatically transfer to such subsequent collector, and such other collector will be deemed the “Collector” (for purposes of such Meta Pass NFT and the Collector License to the underlying Art (as defined below)) and will be subject to these Terms, and (c) you, as the seller or transferor of such Meta Pass NFT, will cease to have any further rights to such Meta Pass NFT or underlying Art.</p>

                                    <p className="fs-6">By placing an order on the Site or through the Services (including by bidding in an auction), you agree that you are submitting a binding offer to purchase a Meta Pass NFT, you agree to pay all applicable fees associated with the Transaction, and you authorize Randomizer Network to automatically charge and collect such fees from your payment instrument or wallet. If you are an Initial Purchaser, then all amounts due are to be paid to Randomizer Network. If you are not the Initial Purchaser of a Meta Pass NFT, then amounts may be paid to the seller of such Meta Pass NFT.</p>

                                    <p className="fs-6">You acknowledge and agree that Randomizer Network receives 5.0% of every Secondary Sale of a Meta Pass NFT (“Royalty”). Randomizer Network has the right to collect Royalties for Randomizer Network sales in perpetuity. As such, if you sell a Meta Pass NFT on a third-party marketplace, you agree to include a statement substantially similar to the following in the description of the NFT: “5.0% Royalty Applies. By purchasing a Meta Pass NFT, you agree to the Terms of Use located at https://randomizer.network/terms-of-sale”</p>

                                    <p className="fs-6">No refunds are permitted except with respect to any statutory warranties or guaranties that cannot be excluded or limited by law.</p>

                                    <p className="fs-6">Taxes</p>
                                    <p className="fs-6">You are responsible for any and all sales, use, value-added and other taxes, duties, and assessments now or hereafter claimed or imposed by any governmental authority, associated with your use of the Services, Perks or Meta Pass NFTs (including, without limitation, any taxes that may become payable as the result of your ownership, transfer, purchase, or sale of a Meta Pass NFT).</p>

                                    <p className="fs-6">Randomizer Network Intellectual Property Rights</p>
                                    <p className="fs-6">You acknowledge and agree that the Services may contain content or features (“Services Content”) that are protected by copyright, patent, trademark, trade secret, or other proprietary rights and laws. Except as expressly authorized by Randomizer Network, you agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute, or create derivative works based on the Services or the Services Content, in whole or in part. Any use of the Services or the Services Content other than as specifically authorized herein is strictly prohibited.</p>

                                    <p className="fs-6">Randomizer Network's name and logos, including the terms Randomizer Network and Meta Pass, are trademarks and service marks of Randomizer Network (collectively the “Randomizer Network Trademarks”). Other, product, and service names and logos used and displayed via the Services may be trademarks or service marks of their respective owners who may or may not endorse or be affiliated with or connected to Randomizer Network. All of these rights are expressly reserved in the name of Randomizer Network and/or its affiliates. Nothing in these Terms or the Services should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of Randomizer Network Trademarks or, other than the rights to the Art (as set forth below), any other intellectual property of Randomizer Network, without Randomizer Network's prior written permission in each instance. All rights in such intellectual property are reserved by Randomizer Network and/or its affiliates, and all goodwill generated from the use of Randomizer Network Trademarks will inure to our exclusive benefit.</p>

                                    <p className="fs-6">RIGHTS TO Meta Pass NFTS YOU OWN</p>
                                    <p className="fs-6">Personal Use. Subject to your continued compliance with these Terms, Randomizer Network grants you a worldwide, royalty-free license to use, copy, and display the digital art represented by your Meta Pass NFT (“Art”), along with any extensions that you choose to create or use, solely for the following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your Meta Pass NFT, provided that the marketplace cryptographically verifies each Meta Pass NFT owner’s rights to display the Art for their Meta Pass NFT to ensure that only the actual owner can display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your Meta Pass NFT, provided that the website/application cryptographically verifies each Meta Pass NFT owner’s rights to display the Art for their Meta Pass NFT to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Meta Pass NFT leaves the website/application.</p>

                                    <p className="fs-6">Commercial Use. Subject to your continued compliance with these Terms, Randomizer Network grants you a worldwide license to use, copy, and display the Art represented by your Meta Pass NFT for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would be the use of the Art to produce and sell merchandise products (e.g., T-Shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of Meta Pass NFT generally, provided that the marketplace cryptographically verifies each Meta Pass NFT owner’s rights to display the Art for their Meta Pass NFT to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of Meta Pass NFT generally, provided that the third party website or application cryptographically verifies each Meta Pass NFT owner’s rights to display the Art for their Meta Pass NFT to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Meta Pass NFT leaves the website/application; or (iii) earning revenue from any of the foregoing.</p>

                                    <p className="fs-6">NO PROFESSIONAL ADVICE; TRANSACTION RISKS</p>
                                    <p className="fs-6">The information on this Site and any information provided in connection with the Services or Perks are provided to Meta Pass NFT owners only and for information only and do not constitute, and should not be construed as, professional advice or a recommendation to purchase, sell, trade, or otherwise transact in any digital asset including any products or services or an invitation, offer or solicitation to engage in any purchase, sale, trade, or other transaction with respect to any digital asset.</p>

                                    <p className="fs-6">The information on this Site and any information provided in connection with the Services or Perks provided to Meta Pass NFT owners are provided solely on the basis that you will make your own transaction decisions, and Randomizer Network does not take account of any person's financial or other objectives, particular needs, or financial situation. In addition, nothing on this Site or any information provided in connection with the Services or Perks provided to Meta Pass NFT owners shall, or is intended to, constitute financial, legal, accounting or tax advice. It is strongly recommended that you seek professional advice before making any transaction decision. Any decision that you make should be based on an assessment of your risks in consultation with your professional adviser(s).</p>

                                    <p className="fs-6">The digital assets about which information is provided on the Site and any information provided in connection with the Services or Perks provided to Meta Pass NFT owners are not viewed by the issuer or sponsor of any such digital assets, or those buying or selling the digital asset, as securities under U.S. laws or relevant applicable laws. As a result it is unlikely that fulsome disclosures from the issuer or sponsor, or any executive officer associated with the digital asset or related protocol have been provided, and others may have better or more information than the information made available to you via the Site, or any information provided in connection with the Services or Perks provided to Meta Pass NFT owners or to which you may independently have access.</p>

                                    <p className="fs-6">There are risks associated with purchasing and holding digital assets. Loss of the full amount of the purchase price is possible. Volatility is highly likely, and some of the protocols and platforms may fail entirely due to forking, flaws in the code, hacking or other malicious attacks.</p>

                                    <p className="fs-6">THESE TERMS DO NOT REPRESENT A COMPLETE STATEMENT OF RISK FACTORS ASSOCIATED WITH THE DIGITAL ASSETS OR PRODUCTS OR SERVICES THAT MAY BE VIEWED OR TRACKED ON THIS SITE OR THAT MAY BE FEATURED OR DISCUSSED IN CONNECTION WITH THE SERVICES OR PERKS FOR Meta Pass NFT OWNERS. YOU SHOULD CONSIDER THESE RISK WARNINGS CAREFULLY AND TAKE APPROPRIATE ADVICE BEFORE TAKING ANY DECISION TO PURCHASE, SELL, TRADE OR OTHERWISE TRANSACT IN A DIGITAL ASSET.</p>

                                    <p className="fs-6">Restrictions</p>
                                    <p className="fs-6">You agree that you will not, and will not permit any third party to, do or attempt to do any of the following without the Randomizer Network's express prior written consent in each case:</p>

                                    <p className="fs-6">interfere with or disrupt the Services or servers or networks connected to the Services in any manner that could negatively affect or inhibit other Users from fully enjoying the Services or that could damage, disable, overburden or impair the functioning of the Services in any manner; violate any applicable local, state, national or international law, or any regulations having the force of law, including but not limited to the U.S. Department of Treasury's Office of Foreign Assets Control (“OFAC”), or which would involve proceeds of any unlawful activity;</p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    )
}
